CREATE TABLE IF NOT EXISTS oficio_categoria_entidad (
  id INT NOT NULL AUTO_INCREMENT,
  codigo VARCHAR(50) NOT NULL,
  nombre VARCHAR(100) NOT NULL,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  creado_en TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_oficio_categoria_entidad_codigo (codigo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO oficio_categoria_entidad (codigo, nombre) VALUES
('COMISARIA', 'COMISARIA'),
('FISCALIA', 'FISCALIA'),
('MILITARES', 'MILITARES'),
('POLICIALES', 'POLICIALES'),
('NECROPSIA', 'NECROPSIA'),
('MUNICIPALIDAD', 'MUNICIPALIDAD'),
('EMPRESA_PUBLICA', 'EMPRESA PUBLICA'),
('EMPRESA_PRIVADA', 'EMPRESA PRIVADA'),
('HOSPITAL', 'HOSPITAL'),
('CLINICA', 'CLINICA'),
('JUZGADO', 'JUZGADO'),
('ASEGURADORA', 'ASEGURADORA'),
('OTRA', 'OTRA');

INSERT IGNORE INTO oficio_categoria_entidad (codigo, nombre)
SELECT DISTINCT categoria, REPLACE(categoria, '_', ' ')
FROM oficio_entidad
WHERE COALESCE(categoria, '') <> '';
