deployment:
  tasks:
    - echo "Iniciando despliegue UIAT Norte..."

    # Crear carpeta si no existe
    - /bin/mkdir -p /home/korkayst/public_html/uiatnorte3

    # Copiar archivos del repo al public_html/uiatnorte3, incluyendo ocultos y sin .git
    - /usr/bin/find . -mindepth 1 -maxdepth 1 ! -name .git -exec /bin/cp -R {} /home/korkayst/public_html/uiatnorte3/ \;

    - echo "Despliegue completado"
