<?php
require __DIR__.'/auth.php';require_login();require __DIR__.'/db.php';
use App\Support\Access;use App\Support\WorkspacePage as Page;
if(!Access::admin()){http_response_code(403);exit('Estadísticas disponibles para el administrador.');}
$from=(string)($_GET['desde']??date('Y-01-01'));$to=(string)($_GET['hasta']??date('Y-m-d'));
foreach([$from,$to] as $d){$date=DateTimeImmutable::createFromFormat('!Y-m-d',$d);if(!$date||$date->format('Y-m-d')!==$d){http_response_code(400);exit('Fechas inválidas.');}}
if($from>$to){http_response_code(400);exit('El inicio debe ser anterior al fin.');}
$params=[$from,$to.' 23:59:59'];
$s=$pdo->prepare("SELECT COUNT(*) total,COALESCE(SUM(latitud IS NOT NULL AND longitud IS NOT NULL),0) georreferenciados,COALESCE(SUM(ubicacion_verificada=1),0) verificados,COALESCE(SUM(estado='Resuelto'),0) resueltos,COALESCE(SUM(fecha_accidente IS NULL),0) fecha_pendiente FROM accidentes_activos WHERE creado_en BETWEEN ? AND ?");$s->execute($params);$counts=$s->fetch();
$s=$pdo->prepare('SELECT estado,COUNT(*) total FROM accidentes_activos WHERE creado_en BETWEEN ? AND ? GROUP BY estado ORDER BY total DESC');$s->execute($params);$states=$s->fetchAll();
$s=$pdo->prepare("SELECT COALESCE(u.nombre,'Sin responsable') responsable,COUNT(*) total FROM accidentes_activos a LEFT JOIN usuarios u ON u.id=a.responsable_id WHERE a.creado_en BETWEEN ? AND ? GROUP BY a.responsable_id,u.nombre ORDER BY total DESC");$s->execute($params);$work=$s->fetchAll();
$s=$pdo->prepare('SELECT COUNT(*) total,COUNT(asignado_en) asignadas,AVG(TIMESTAMPDIFF(SECOND,registrado_en,asignado_en))/60 minutos FROM comunicaciones_guardia WHERE eliminado_en IS NULL AND registrado_en BETWEEN ? AND ?');$s->execute($params);$calls=$s->fetch();
if(($_GET['exportar']??'')==='csv'){
    header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="estadisticas_agregadas.csv"');$out=fopen('php://output','w');fwrite($out,"\xEF\xBB\xBF");
    fputcsv($out,['Indicador','Valor','Desde','Hasta'],';', '"', '');foreach($counts as $k=>$v)fputcsv($out,[$k,$v,$from,$to],';','"','');foreach($states as $r)fputcsv($out,['Estado: '.$r['estado'],$r['total'],$from,$to],';','"','');
    fputcsv($out,['Comunicaciones',$calls['total'],$from,$to],';','"','');fputcsv($out,['Comunicaciones asignadas',$calls['asignadas'],$from,$to],';','"','');fputcsv($out,['Minutos promedio registro a asignación',$calls['minutos']??'Sin datos',$from,$to],';','"','');fclose($out);exit;
}
Page::start('Estadísticas de gestión');
echo '<section><form method="get"><div class="grid"><label>Registro desde<input type="date" name="desde" value="'.Page::escape($from).'" required></label><label>Registro hasta<input type="date" name="hasta" value="'.Page::escape($to).'" required></label></div><button>Aplicar período</button></form><p class="muted">El período usa la fecha de registro en el sistema, no la fecha del accidente. Se excluyen expedientes y comunicaciones eliminados.</p><a href="?'.Page::escape(http_build_query(['desde'=>$from,'hasta'=>$to,'exportar'=>'csv'])).'">Descargar indicadores agregados para análisis</a></section><div class="metrics">';
foreach(['total'=>'Expedientes registrados','georreferenciados'=>'Con coordenadas','verificados'=>'Ubicación verificada','resueltos'=>'Resueltos'] as $k=>$label)echo '<div class="metric">'.$label.'<strong>'.(int)$counts[$k].'</strong></div>';echo '</div><div class="grid"><section><h2>Estado de expedientes</h2><table><tr><th>Estado</th><th>Total</th></tr>';foreach($states as $r)echo '<tr><td>'.Page::escape($r['estado']).'</td><td>'.$r['total'].'</td></tr>';echo '</table></section><section><h2>Carga por responsable</h2><table><tr><th>JEFE EMI</th><th>Expedientes</th></tr>';foreach($work as $r)echo '<tr><td>'.Page::escape($r['responsable']).'</td><td>'.$r['total'].'</td></tr>';echo '</table></section></div><section><h2>Atención de comunicaciones</h2><p>Comunicaciones: <strong>'.(int)$calls['total'].'</strong> · Asignadas: <strong>'.(int)$calls['asignadas'].'</strong></p><p>Tiempo promedio desde registro hasta asignación: <strong>'.($calls['minutos']===null?'Sin datos':number_format((float)$calls['minutos'],1).' minutos').'</strong>.</p><p class="muted">El promedio utiliza únicamente comunicaciones asignadas. Las nuevas fechas de gestión se registran desde esta implementación; la asignación histórica no demuestra el tiempo de atención original. Las coordenadas antiguas quedan sin verificar hasta revisión del responsable.</p><a href="accidente_mapa.php">Abrir mapa de accidentes</a></section>';Page::end();
