<?php
if (PHP_SAPI !== 'cli' || !isset($p) || !str_starts_with((string)$p->query('SELECT DATABASE()')->fetchColumn(), 'uiat_rbac_test_')) exit;
// Incluido por multiusuario_integration.php, dentro de la copia temporal.
actor($p,1);
$userService=new \App\Services\UserService(new \App\Repositories\UserRepository($p));
$registration=['nombre'=>'Usuario CIP de prueba','email'=>'cip-test@example.invalid','cip'=>'009812345','rol'=>'adjunto','grado'=>'ST3.PNP'];
$newUser=$userService->create($registration,'admin');
$login=new \App\Services\LoginService($p);
$u=$login->authenticate($registration['cip'],$registration['cip']);
check((int)$u['id']===$newUser && (int)$u['must_change_password']===1,'nuevo usuario ingresa con CIP y debe cambiar contraseña');
check($u['cip']==='009812345' && $u['pass_hash']!==$registration['cip'],'CIP conserva ceros y contraseña almacenada como hash');
deny(fn()=>$userService->create(array_merge($registration,['email'=>'otro-cip@example.invalid']),'admin'),'CIP duplicado rechazado');
deny(fn()=>$userService->create(array_merge($registration,['cip'=>'AB123']),'admin'),'CIP no numérico rechazado');
\App\Services\LoginService::beginSession($u);
check(empty($_SESSION['user']) && \App\Services\LoginService::pendingSetup()!==null,'contraseña inicial no concede sesión operativa');
check(\App\Support\Auth::postLoginDestination()==='cambiar_clave.php','primer acceso dirige al cambio obligatorio');
$pending=\App\Services\LoginService::pendingSetup();
foreach(['sinmayuscula1!','SINMINUSCULA1!','SinNumeros!!','SinSimbolo123','Aa1!'] as $weak)deny(fn()=>$login->completeSetup($pending,$weak,$weak),'rechaza contraseña que incumple composición o longitud');
deny(fn()=>$login->completeSetup($pending,'NuevaClave123!','OtraClave123!'),'confirmación distinta rechazada');
$p->exec('SET @actor_id='.$newUser.',@rbac_password_change=1');
deny(fn()=>$p->exec("UPDATE usuarios SET rol='admin',must_change_password=0,auth_version=auth_version+1 WHERE id=$newUser"),'primer acceso no permite escalar el perfil');
$p->exec('SET @rbac_password_change=NULL,@actor_id=0');
$complete=$login->completeSetup($pending,'NuevaClave123!','NuevaClave123!');
\App\Services\LoginService::beginSession($complete);
check((int)$_SESSION['user']['id']===$newUser && \App\Services\LoginService::pendingSetup()===null,'nueva contraseña habilita sesión normal');
check(\App\Support\Auth::postLoginDestination()==='index.php','ingreso completo dirige al panel');
deny(fn()=>$login->authenticate($registration['cip'],$registration['cip']),'CIP deja de funcionar como contraseña');
check((int)$login->authenticate($registration['cip'],'NuevaClave123!')['id']===$newUser,'nueva contraseña funciona con CIP');
check((int)$login->authenticate($registration['email'],'NuevaClave123!')['id']===$newUser,'correo sigue disponible para cuentas existentes');
deny(fn()=>$login->completeSetup($pending,'SegundaClave123!','SegundaClave123!'),'credencial temporal no puede reutilizarse');
actor($p,1);
$p->prepare('UPDATE usuarios SET pass_hash=?,must_change_password=1 WHERE id=?')->execute([password_hash('TemporalNueva123!',PASSWORD_DEFAULT),$newUser]);
$reset=$login->authenticate($registration['cip'],'TemporalNueva123!');
check((int)$reset['auth_version']>(int)$complete['auth_version'],'restablecimiento invalida versión de sesiones anteriores');
\App\Services\LoginService::beginSession($reset);$pending=\App\Services\LoginService::pendingSetup();
$expired=$pending;$expired['expires']=time()-1;
deny(fn()=>$login->completeSetup($expired,'FuturaClave123!','FuturaClave123!'),'acceso temporal vencido rechazado');
actor($p,1);$p->exec("UPDATE usuarios SET activo=0 WHERE id=$newUser");
deny(fn()=>$login->completeSetup($pending,'FuturaClave123!','FuturaClave123!'),'usuario desactivado no completa el primer acceso');
$logs=$p->query("SELECT antes,despues FROM auditoria WHERE tabla='usuarios' AND registro_id='$newUser'")->fetchAll();
check(!str_contains(json_encode($logs),'NuevaClave123!') && !str_contains(json_encode($logs),'pass_hash'),'auditoría no almacena contraseñas ni hashes');
unset($_SESSION['password_setup']);
